export const ADD_TO_PENDING: 'ADD_TO_PENDING' = 'ADD_TO_PENDING'
export const ADD_TO_ACCEPTED: 'ADD_TO_ACCEPTED' = 'ADD_TO_ACCEPTED'
export const DELETE_FROM_PENDING: 'DELETE_FROM_PENDING' = 'DELETE_FROM_PENDING'
export const ACCEPT_ORDER: 'ACCEPT_ORDER' = 'ACCEPT_ORDER'

